vim.keymap.set("n", "s", function()
	require("flash").jump()
end)
vim.keymap.set("n", "S", function()
	require("flash").jump({ pattern = vim.fn.expand("<cword>") })
end)
vim.keymap.set("n", "<leader>ts", function()
	require("flash").treesitter()
end)
